"""Host model, persistent state and ~/.ssh/config rendering."""

from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from . import compat, secrets
from .compat import BEGIN_MARKER, END_MARKER, SSH_CONFIG, STATE_FILE, ensure_dirs, secure_file

DEFAULT_MONITORS = {
    "gpu": True,
    "cpu": True,
    "users": True,
    "processes": True,
}


@dataclass
class Host:
    alias: str
    hostname: str = ""
    user: str = ""
    port: str = "22"
    identity_file: str = ""
    proxy_jump: str = ""
    dashboard: bool = False
    monitors: dict[str, bool] = field(default_factory=lambda: dict(DEFAULT_MONITORS))
    notes: str = ""
    source: str = "managed"
    extra: dict[str, str] = field(default_factory=dict)

    @property
    def target(self) -> str:
        user = f"{self.user}@" if self.user else ""
        port = f":{self.port}" if self.port and self.port != "22" else ""
        host = self.hostname or self.alias
        return f"{user}{host}{port}"


def load_state() -> dict[str, Any]:
    ensure_dirs()
    if not STATE_FILE.exists():
        return {"hosts": {}, "pins": []}
    try:
        data = json.loads(STATE_FILE.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError, UnicodeDecodeError):
        return {"hosts": {}, "pins": []}
    data.setdefault("hosts", {})
    data.setdefault("pins", [])
    return data


def save_state(data: dict[str, Any]) -> None:
    ensure_dirs()
    tmp = STATE_FILE.with_name(f"{STATE_FILE.name}.{os.getpid()}.tmp")
    tmp.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    secure_file(tmp)
    os.replace(tmp, STATE_FILE)
    secure_file(STATE_FILE)


def validate_alias(alias: str) -> str | None:
    if not alias:
        return "Alias is required."
    if re.search(r"\s", alias):
        return "Alias cannot contain whitespace."
    if any(ch in alias for ch in "*?[]!"):
        return "Alias cannot contain SSH pattern characters."
    if alias.startswith("-"):
        return "Alias cannot start with '-'."
    return None


def parse_bool(value: str | None, default: bool = False) -> bool:
    if value is None or value == "":
        return default
    return value.strip().lower() in {"1", "y", "yes", "true", "on", "enable", "enabled"}


def host_from_dict(alias: str, raw: dict[str, Any], source: str = "managed") -> Host:
    extra = {k: str(v) for k, v in raw.get("extra", {}).items()}
    proxy_jump = str(
        raw.get("proxy_jump")
        or raw.get("ProxyJump")
        or extra.pop("ProxyJump", "")
        or extra.pop("proxyjump", "")
    )
    monitors = dict(DEFAULT_MONITORS)
    if isinstance(raw.get("monitors"), dict):
        monitors.update({k: bool(v) for k, v in raw["monitors"].items() if k in DEFAULT_MONITORS})
    return Host(
        alias=alias,
        hostname=str(raw.get("hostname") or raw.get("HostName") or ""),
        user=str(raw.get("user") or raw.get("User") or ""),
        port=str(raw.get("port") or raw.get("Port") or "22"),
        identity_file=str(raw.get("identity_file") or raw.get("IdentityFile") or ""),
        proxy_jump=proxy_jump,
        dashboard=bool(raw.get("dashboard", False)),
        monitors=monitors,
        notes=str(raw.get("notes") or ""),
        source=source,
        extra=extra,
    )


def host_to_dict(host: Host) -> dict[str, Any]:
    return {
        "hostname": host.hostname,
        "user": host.user,
        "port": host.port or "22",
        "identity_file": host.identity_file,
        "proxy_jump": host.proxy_jump,
        "dashboard": host.dashboard,
        "monitors": host.monitors,
        "notes": host.notes,
        "extra": host.extra,
    }


def managed_hosts_from_state(data: dict[str, Any]) -> dict[str, Host]:
    return {alias: host_from_dict(alias, raw, "managed") for alias, raw in data.get("hosts", {}).items()}


def strip_managed_block(text: str) -> str:
    pattern = re.compile(
        rf"\n?{re.escape(BEGIN_MARKER)}\n.*?\n{re.escape(END_MARKER)}\n?",
        re.DOTALL,
    )
    stripped = pattern.sub("\n", text)
    return stripped.rstrip() + ("\n" if stripped.strip() else "")


def _config_path(identity_file: str) -> str:
    """Quote IdentityFile paths that contain spaces (common on Windows)."""
    if identity_file and " " in identity_file and not identity_file.startswith('"'):
        return f'"{identity_file}"'
    return identity_file


def render_managed_block(hosts: dict[str, Host]) -> str:
    lines = [
        BEGIN_MARKER,
        f"# Generated by sshkit. Passwords are stored in the {secrets.store_label()}.",
    ]
    for alias in sorted(hosts):
        host = hosts[alias]
        lines.append("")
        lines.append(f"Host {host.alias}")
        if host.hostname:
            lines.append(f"  HostName {host.hostname}")
        if host.user:
            lines.append(f"  User {host.user}")
        if host.port and host.port != "22":
            lines.append(f"  Port {host.port}")
        if host.identity_file:
            lines.append(f"  IdentityFile {_config_path(host.identity_file)}")
            lines.append("  IdentitiesOnly yes")
        if host.proxy_jump:
            lines.append(f"  ProxyJump {host.proxy_jump}")
        lines.append("  ServerAliveInterval 30")
        lines.append("  StrictHostKeyChecking accept-new")
        for key, value in sorted(host.extra.items()):
            if key and value:
                lines.append(f"  {key} {value}")
        if host.notes:
            safe_note = host.notes.replace("\n", " ").strip()
            lines.append(f"  # sshkit note: {safe_note}")
    lines.append("")
    lines.append(END_MARKER)
    lines.append("")
    return "\n".join(lines)


def _write_config(text: str) -> None:
    # newline="\n": OpenSSH on Windows reads LF fine, and CRLF churn in the
    # config file makes diffs noisy for users who sync their dotfiles.
    SSH_CONFIG.write_text(text, encoding="utf-8", newline="\n")
    secure_file(SSH_CONFIG)


def write_ssh_config(data: dict[str, Any]) -> None:
    ensure_dirs()
    current = SSH_CONFIG.read_text(encoding="utf-8", errors="replace") if SSH_CONFIG.exists() else ""
    unmanaged = strip_managed_block(current)
    block = render_managed_block(managed_hosts_from_state(data))
    _write_config(block + ("\n" + unmanaged if unmanaged.strip() else ""))


def remove_alias_from_unmanaged_config(alias: str) -> bool:
    if not SSH_CONFIG.exists():
        return False
    text = strip_managed_block(SSH_CONFIG.read_text(encoding="utf-8", errors="replace"))
    lines = text.splitlines()
    out: list[str] = []
    changed = False
    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()
        parts = stripped.split(None, 1)
        if len(parts) >= 2 and parts[0].lower() == "host":
            block = [line]
            i += 1
            while i < len(lines):
                next_line = lines[i]
                next_parts = next_line.strip().split(None, 1)
                if len(next_parts) >= 2 and next_parts[0].lower() == "host":
                    break
                block.append(next_line)
                i += 1
            aliases = parts[1].split()
            if alias in aliases:
                changed = True
                aliases = [a for a in aliases if a != alias]
                if aliases:
                    indent = line[: len(line) - len(line.lstrip())]
                    block[0] = f"{indent}Host {' '.join(aliases)}"
                    out.extend(block)
                continue
            out.extend(block)
            continue
        out.append(line)
        i += 1

    if changed:
        data = load_state()
        unmanaged = "\n".join(out).rstrip() + ("\n" if any(line.strip() for line in out) else "")
        block = render_managed_block(managed_hosts_from_state(data))
        _write_config(block + ("\n" + unmanaged if unmanaged.strip() else ""))
    return changed


def parse_ssh_config_hosts(path: Path | None = None) -> dict[str, Host]:
    config = path or SSH_CONFIG
    if not config.exists():
        return {}
    text = strip_managed_block(config.read_text(encoding="utf-8", errors="replace"))
    hosts: dict[str, Host] = {}
    current_aliases: list[str] = []
    current_values: dict[str, str] = {}

    def flush() -> None:
        nonlocal current_aliases, current_values
        if not current_aliases:
            return
        for alias in current_aliases:
            if any(ch in alias for ch in "*?[]!"):
                continue
            hosts.setdefault(
                alias,
                Host(
                    alias=alias,
                    hostname=current_values.get("hostname", ""),
                    user=current_values.get("user", ""),
                    port=current_values.get("port", "22"),
                    identity_file=current_values.get("identityfile", ""),
                    proxy_jump=current_values.get("proxyjump", ""),
                    source="config",
                ),
            )
        current_aliases = []
        current_values = {}

    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        parts = stripped.split(None, 1)
        if len(parts) < 2:
            continue
        key = parts[0].lower()
        value = parts[1].strip()
        if key == "host":
            flush()
            current_aliases = value.split()
            current_values = {}
        elif current_aliases and key in {"hostname", "user", "port", "identityfile", "proxyjump"}:
            current_values[key] = value
    flush()
    return hosts


def all_hosts(data: dict[str, Any]) -> list[Host]:
    managed = managed_hosts_from_state(data)
    config_hosts = parse_ssh_config_hosts()
    merged = dict(config_hosts)
    merged.update(managed)
    pins = set(data.get("pins", []))
    return sorted(merged.values(), key=lambda h: (0 if h.alias in pins else 1, h.alias.lower()))


def find_host(alias: str) -> Host | None:
    for host in all_hosts(load_state()):
        if host.alias == alias:
            return host
    return None


def enabled_monitors(host: Host, overrides: dict[str, bool] | None = None) -> list[str]:
    config = dict(DEFAULT_MONITORS)
    config.update(host.monitors or {})
    if overrides:
        config.update(overrides)
    return [name for name in DEFAULT_MONITORS if config.get(name)]


def format_monitors(monitors: dict[str, bool]) -> str:
    config = dict(DEFAULT_MONITORS)
    config.update(monitors or {})
    return ",".join(name for name in DEFAULT_MONITORS if config.get(name))


def parse_monitor_list(value: str | None, default: dict[str, bool]) -> dict[str, bool]:
    if value is None or value.strip() == "":
        return dict(default)
    config = {name: False for name in DEFAULT_MONITORS}
    tokens = [token.strip().lower() for token in value.split(",") if token.strip()]
    if any(token in {"none", "off", "disabled"} for token in tokens):
        return config
    for token in tokens:
        if token in {"all", "*"}:
            return dict(DEFAULT_MONITORS)
        if token in DEFAULT_MONITORS:
            config[token] = True
    return config


__all__ = [
    "DEFAULT_MONITORS",
    "Host",
    "all_hosts",
    "compat",
    "enabled_monitors",
    "find_host",
    "format_monitors",
    "host_from_dict",
    "host_to_dict",
    "load_state",
    "managed_hosts_from_state",
    "parse_bool",
    "parse_monitor_list",
    "parse_ssh_config_hosts",
    "remove_alias_from_unmanaged_config",
    "render_managed_block",
    "save_state",
    "strip_managed_block",
    "validate_alias",
    "write_ssh_config",
]
